### ISSUE TITLE
starting day of the week

### ISSUE THREAD

**Issue by zhanglongqi** [limbara/vue-time-date-range-picker#2]
Is it possible that add an option that can set the starting day of the week to Monday?

**Comment by limbara** [comment]
It's possible, would you like to do this feature ? currently i had the calendar locale from moment to decide whether the day of the week starts from Monday or Sunday

**Comment by zhanglongqi** [comment]
I just start to learn the frontend programming. still struggling to learn how to use all the components. So sorry I can not help.

**Comment by limbara** [comment]
Feature already added in version v1.2.0
