### ISSUE TITLE
Reset Event

### ISSUE THREAD

**Issue by VQD-GertWittouck** [limbara/vue-time-date-range-picker#22]
Hi,

I was wondering if it is possible to emit the "on-reset" event on the "CalendarDialog" as event in the DatePicker component so that whoever uses the DatePicker component can perform some additional actions on the reset event?

The 'on-reset' event is emitted from the CalendarDialog
`    onClickButtonReset() {
      this.selectedStartDate = null;
      this.selectedEndDate = null;
      this.isAllDay = false;
      this.$emit('on-reset');
    },`

But once the "onReset" method of the DatePicker that listens to this event isn't emitting the event to the outside:
`    onReset() {
      this.selectedStartDate = null;
      this.selectedEndDate = null;
    }`
    
I am using version 1.x as the VueJS version of my project is 2.x

**Comment by limbara** [comment]
hhhmm, a small change. i'll work on it maybe on weekend

**Comment by limbara** [comment]
Release on [v1.6.0](https://github.com/limbara/vue-time-date-range-picker/releases/tag/v1.6.0)
