### ISSUE TITLE
time error while input

### ISSUE THREAD

**Issue by pho-76242** [limbara/vue-time-date-range-picker#3]
when input time (no use arrow-control), time-value return "00:00".
Is it a bug?

**Comment by limbara** [comment]
can you explain more on how it happened ?

**Comment by pho-76242** [comment]
if you pick time (not use arrow-control), time value will return "00:00". Looking forward to your help!
<img width="656" alt="Screen Shot 2020-10-22 at 11 11 50" src="https://user-images.githubusercontent.com/58925706/96824168-5aeb9c00-1458-11eb-9478-3e8200cd7c44.png">
