### ISSUE TITLE
demos does not work

### ISSUE THREAD

**Issue by scenaristeur** [limbara/vue-time-date-range-picker#35]
https://codepen.io/limbara/pen/ZEQxoZZ

![image](https://github.com/limbara/vue-time-date-range-picker/assets/4020744/00497076-352e-4b6a-b59c-68e25c17b424)

and https://codesandbox.io/s/example-vue-time-date-range-picker-byw7g
![image](https://github.com/limbara/vue-time-date-range-picker/assets/4020744/db28021c-2fb8-4561-af7b-f9f808d5a4b6)

**Comment by limbara** [comment]
thanks for letting me know @scenaristeur , issue already fixed in [Release v2.1.2](https://github.com/limbara/vue-time-date-range-picker/releases)
