### ISSUE TITLE
Is there any way to change `apply-button`'s type attribute from `submit` to `button`?

### ISSUE THREAD

**Issue by hono-n** [limbara/vue-time-date-range-picker#39]
Hi, I'm using `date-picker`, and I'm wondering if there's any option to change the type attribute of `apply-button` from  `submit` to `button`, since I don't want the submit event triggered when I click apply button 🙇‍♀️ 

I'm using [version1](https://github.com/limbara/vue-time-date-range-picker/tree/version-1)

I'll really appreciate if you could have a check. Thank you!

**Comment by limbara** [comment]
i don't think i have specified any type attribute for the apply button and when i looked it up, i found out that by default any buttons that are inside form element is treated as 'submit'. I haven't think of any other way to fix this except by modifying the codes, but i do find a way to prevent form submit from this component apply button. 

by conditionally checking the event.submitter property, check what that button is and event.preventDefault() to prevent the form from submitting.

below i attach this code example

```vue
<template>
      <form @submit="onSubmit">
            <date-picker :dateInput="dateInput" :initialDates="dates1" />
            <button type="submit">
              Submit
            </button>
      </form>
</template>

<script>
export default {
  ...,
  methods: {
    onSubmit: (e) => {
      if (e.submitter.classList[0] === 'vdpr-datepicker__button') {
        e.preventDefault();
      }
      
      console.log('on Submit Ran', e);
    },
  },
};
</script>
```

**Comment by hono-n** [comment]
Thank you so much for kindly giving me a suggestion! ✨ 
I've actually tried the way you've suggested, but since I'm using Rails framework, the event handler of Rails framework listens the submit event first and makes the actual submit button of the form disabled, and after that the `preventDefault()` is executed. So I've encountered the problem that the submit button of the form remains disabled one after I click the component's `apply-button`.
Do you think of any good idea to resolve this problem...? 🙏

**Comment by limbara** [comment]
unfortunately i don't know much about how Rails framework form works, sounds like for some reason the form event listener is not added ? or the Rails have it's own javascript event listener installed on the form ?, anyway you have to find out how to submit the form yourself by using javascript. the form is on the client side when it's rendered and javascript should be able to handle it.

maybe you could try adding 
```javascript
e.stopPropagation(); // Prevent the event from bubbling up
```

**Comment by hono-n** [comment]
Thank you so much for your reaction !
I've found out the way to resolve this problem by disabling the Rails framework's behavior and implementing the alternative by my own 🙇‍♀️
Thank you so much for your kindness of replying to my message, and thinking of the solution.
Your library helps my developing a product a lot :)
