### ISSUE TITLE
can we manually reset the date range picker from another parent component?

### ISSUE THREAD

**Issue by Dhamu143** [limbara/vue-time-date-range-picker#40]
I have integrated this package in child component and now i want to reset the date range picker from the parent component. so is there any method that can we can manually emit the @on-reset event ?

**Comment by limbara** [comment]
i think you can use ref to execute `onReset` method manually, refer to https://vuejs.org/guide/essentials/template-refs.html#ref-on-component

**Comment by Dhamu143** [comment]
I tried this but this will not able to trigger the @on-reset  on vue-time-date-range-picker

**Comment by limbara** [comment]
If i understood you correctly, i've made an example in [codesandbox](https://codesandbox.io/p/devbox/hfrfk4) that reset the date picker externally from the parent component. In the example, i use ref to trigger DatePicker reset event by `onReset` method and force the DatePicker to rerender using `:key`. What i did is probably not clean but it does the job.

We'll probably update the components to be able to receive ref props for the component inside DatePicker

**Comment by Dhamu143** [comment]
Your solution does not work in my project. in my project the datepicker and reset buttons are two different components. and As i tried your solution i got error of InstanceType and even if i tried to fix those issue the overall solution does not work. 
anyway thanks for your help. i really appreciate :)

**Comment by limbara** [comment]
#46 introducing v-model binding to reset date from outside component
