### ISSUE TITLE
Wrong weekday when first day of week is set to Monday

### ISSUE THREAD

**Issue by schafo** [limbara/vue-time-date-range-picker#5]
If the "first day of the week" option is set to Monday (`is-monday-first=true`) and a month begins on a Sunday, then there's a bug that causes the weekdays of that monrth to be off by one.

Instead of starting on a Sunday, it incorrectly starts on a Monday. (Below the ones on the left are correct.)

![march2020](https://user-images.githubusercontent.com/42965475/111188538-0d113500-85ad-11eb-8000-c37cc02d28f0.png)
![november2020](https://user-images.githubusercontent.com/42965475/111188540-0da9cb80-85ad-11eb-843d-aa3bcc58d59f.png)

This bug does not seem to affect months starting on other days.

**Comment by limbara** [comment]
yeah a bug, do you want to fix it @schafo ?

**Comment by schafo** [comment]
Happy to have a go at it. I tried to have a quick look when I discovered it to see if there was something I could spot immediately, but nothing stood out. I'll take a closer look.

**Comment by limbara** [comment]
Release on v1.2.3
