### ISSUE TITLE
How to specify the `date-input` prop?

### ISSUE THREAD

**Issue by lobin-z0x50** [limbara/vue-time-date-range-picker#8]
Hello.

This is a very nice looking and customizable component.
I am considering whether to use this component in m product.

I have a question.
How should I write the `date-input` specification?

I tried to write it as follows, but it was not reflected.
```vue
<div id="app">
  <date-picker 
    language="ja"
    :date-input="{labelStarts: '開始'}"
    />
</div>
```
![スクリーンショット 2021-06-08 21 33 34](https://user-images.githubusercontent.com/11419109/121185603-320dff00-c8a1-11eb-8504-13787702efa4.png)

Only the `inputClass` seems to be reflected in the `input` element from which the dialog is displayed.

**Comment by limbara** [comment]
use "calendar-date-input" props as documented in [calendar date input config](https://github.com/limbara/vue-time-date-range-picker#c-date-input)

**Comment by lobin-z0x50** [comment]
Thank you very much !
I finally understand now.
